defaultPortal: stanby
portals:
  - name: stanby
    portalId: 21620163
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJHPuPfnMBILAA0AAAAAAEwDQAIYw8unCiC1i-0VKO7pDDIUVXCdsF2hugnZSl7VQyN8Uj7Pmy86NwAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcAAAAAPABABgBEAGAAAAAAAAAAAAAAAAAAMAJCFIrufTyoCkwiT7NZ5WA-ASidif2XSgNuYTFSAFoA
        expiresAt: '2023-02-23T15:39:42.354Z'
    personalAccessKey: >-
      CiQ3NzVkYTE3ZS01NDE1LTQzYjAtOTdkNC1mYWZhZTY2YjI1NTMQw8unChi1i-0VKhkABeaRgroYPpZ1k7U0X3sfQytT9vvAIqI8SgNuYTE
