defaultPortal: stanby
portals:
  - name: stanby
    portalId: 21620163
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLqLhJroMBILAA0AAAAAAEwDQAIYw8unCiC1i-0VKO7pDDIU-XlNYfbS88pnGtI02hRmSesWru06NwAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcAAAAAPABABgBEAGAAAAAAAAAAAAAAAAAAMAJCFBaRKY5pRastwJuMSCt9utBSs24ySgNuYTFSAFoA
        expiresAt: '2023-02-24T11:48:42.045Z'
    personalAccessKey: >-
      CiQ3NzVkYTE3ZS01NDE1LTQzYjAtOTdkNC1mYWZhZTY2YjI1NTMQw8unChi1i-0VKhkABeaRgroYPpZ1k7U0X3sfQytT9vvAIqI8SgNuYTE
