defaultPortal: stanby
portals:
  - name: stanby
    portalId: 21620163
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNvu06XnMBILAA0AAAAAAEwDQAIYw8unCiC1i-0VKO7pDDIUE44E8uzMU2OBzwpFlz7bIMNZQtw6NwAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcAAAAAPABABgBEAGAAAAAAAAAAAAAAAAAAMAJCFM29jkBvCPd4ivqFXZ1Aoln9l5IpSgNuYTFSAFoA
        expiresAt: '2023-02-21T16:01:02.300Z'
    personalAccessKey: >-
      CiQ3NzVkYTE3ZS01NDE1LTQzYjAtOTdkNC1mYWZhZTY2YjI1NTMQw8unChi1i-0VKhkABeaRgroYPpZ1k7U0X3sfQytT9vvAIqI8SgNuYTE
